"""changed topic id to uuid

Revision ID: 014ed2f40b7e
Revises: 9b5a33344505
Create Date: 2025-12-31 11:11:16.812333

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '014ed2f40b7e'
down_revision: Union[str, Sequence[str], None] = '9b5a33344505'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("topic_keywords")
    op.drop_table("topic_experience_ranges")
    op.drop_table("premium_topic_adjustments")
    op.drop_table("topics")
    op.create_table(
        "topics",
        sa.Column("id", sa.UUID(), primary_key=True),
        sa.Column("code", sa.String(20), nullable=False, unique=True),
        sa.Column("classification", sa.String(20), nullable=False),
        sa.Column("description", sa.Text(), nullable=False),
        sa.Column("published", sa.Boolean(), default=False),
        sa.Column("display_names", sa.ARRAY(sa.String()), nullable=False),
        sa.Column("created_at", sa.DateTime()),
        sa.Column("updated_at", sa.DateTime()),
    )
    op.create_table(
        "premium_topic_adjustments",
        sa.Column("id", sa.Integer(), primary_key=True),
        sa.Column(
            "topic_id",
            sa.UUID(),
            sa.ForeignKey("topics.id", ondelete="CASCADE"),
            nullable=False,
        ),
        sa.Column("interview_type", sa.String(30), nullable=False),
        sa.Column("adjustment_percentage", sa.Numeric(8, 2), default=0),
        sa.Column("created_at", sa.DateTime()),
        sa.Column("updated_at", sa.DateTime()),
    )
    op.create_table(
        "topic_experience_ranges",
        sa.Column("id", sa.Integer(), primary_key=True),
        sa.Column(
            "topic_id",
            sa.UUID(),
            sa.ForeignKey("topics.id", ondelete="CASCADE"),
            nullable=False,
        ),
        sa.Column(
            "experience_range_id",
            sa.Integer(),
            sa.ForeignKey("experience_ranges.id", ondelete="CASCADE"),
            nullable=False,
        ),
    )

    op.create_table(
        "topic_keywords",
        sa.Column(
            "topic_id",
            sa.UUID(),
            sa.ForeignKey("topics.id", ondelete="CASCADE"),
            primary_key=True,
        ),
        sa.Column(
            "keyword_id",
            sa.Integer(),
            sa.ForeignKey("keywords.id", ondelete="CASCADE"),
            primary_key=True,
        ),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("topic_keywords", if_exists=True)
    op.drop_table("topic_experience_ranges", if_exists=True)
    op.drop_table("premium_topic_adjustments", if_exists=True)
    op.drop_table("topics", if_exists=True)

    # ### end Alembic commands ###
