"""initial fixed schema

Revision ID: 9b5a33344505
Revises: 
Create Date: 2025-12-30 11:18:20.511799

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '9b5a33344505'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('experience_ranges',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('label', sa.String(length=50), nullable=False),
    sa.Column('sort_order', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('keywords',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('keyword', sa.String(length=50), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('keyword')
    )
    op.create_table('topics',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('code', sa.String(length=20), nullable=False),
    sa.Column('classification', sa.String(length=20), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('published', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.Column('display_names', postgresql.ARRAY(sa.String()), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('code')
    )
    op.create_table('base_pricing',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('classification', sa.String(length=20), nullable=False),
    sa.Column('interview_type', sa.String(length=30), nullable=False),
    sa.Column('experience_level_id', sa.Integer(), nullable=False),
    sa.Column('duration_mins', sa.Integer(), nullable=True),
    sa.Column('domestic_price', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('international_price', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['experience_level_id'], ['experience_ranges.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('premium_topic_adjustments',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('topic_id', sa.Integer(), nullable=False),
    sa.Column('interview_type', sa.String(length=30), nullable=False),
    sa.Column('adjustment_percentage', sa.Numeric(precision=8, scale=2), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['topic_id'], ['topics.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('topic_experience_ranges',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('topic_id', sa.Integer(), nullable=False),
    sa.Column('experience_range_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['experience_range_id'], ['experience_ranges.id'], ),
    sa.ForeignKeyConstraint(['topic_id'], ['topics.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('topic_keywords',
    sa.Column('topic_id', sa.Integer(), nullable=False),
    sa.Column('keyword_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['keyword_id'], ['keywords.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['topic_id'], ['topics.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('topic_id', 'keyword_id')
    )

    experience_ranges = sa.table(
        "experience_ranges",
        sa.column("id", sa.Integer),
        sa.column("label", sa.String),
        sa.column("sort_order", sa.Integer),
    )

    op.bulk_insert(
        experience_ranges,
        [
            {"id": 1, "label": "0-2 years", "sort_order": 1},
            {"id": 2, "label": "2-5 years", "sort_order": 2},
            {"id": 3, "label": "5-10 years", "sort_order": 3},
            {"id": 4, "label": "10-15 years", "sort_order": 4},
            {"id": 5, "label": "15-20 years", "sort_order": 5},
            {"id": 6, "label": "20-25 years", "sort_order": 6},
            {"id": 7, "label": "25+ years", "sort_order": 7},
        ],
    )

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('topic_keywords')
    op.drop_table('topic_experience_ranges')
    op.drop_table('premium_topic_adjustments')
    op.drop_table('base_pricing')
    op.drop_table('topics')
    op.drop_table('keywords')
    op.drop_table('experience_ranges')
    # ### end Alembic commands ###
